import Main from '@/components/Home/Home';
// import { Inter } from 'next/font/google';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>xAPI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-slate-300 pt-16">
        <div className="container mx-auto min-h-screen border-2 rounded-md border-slate-50 p-4 bg-slate-200">
          <p className="text-center text-orange-500 font-semibold text-2xl">
            xAPI implementation
          </p>
          <Main />
        </div>
      </main>
    </>
  );
}
